version: "2.2"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "61635:61635"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/frontend
