version: "2.2"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "61635:61635"
    volumes:
      - ./backend:/app/backend
      - ./backend/node_modules
